name: login_app
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  micro_app_dependencies:
    git: https://github.com/WelintonPrediger/micro_app_dependencies.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  mobx_codegen: ^2.0.7
  modular_test: ^2.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg

vars:
  runner: flutter pub run build_runner
  clean: flutter clean
  get: flutter pub get

scripts:
  build_and_clean: $clean & $get & $runner build --delete-conflicting-outputs
  build_delete_conflict: $runner build --delete-conflicting-outputs
  build_watch: $runner watch
